set(CUDA_TOOLKIT_ROOT_DIR "$ENV{OECORE_NATIVE_SYSROOT}${_cuda_prefix}" CACHE PATH "" FORCE)
set(CUDA_TOOLKIT_TARGET_DIR "${CMAKE_SYSROOT}/usr/local/cuda-$ENV{CUDA_VERSION}" CACHE PATH "" FORCE)
set(CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES "${CUDA_TOOLKIT_TARGET_DIR}/include" CACHE STRING "" FORCE)
