#@TYPE: Machine
#@NAME: Nvidia IGX Thor dev kit
#@DESCRIPTION: Nvidia IGX Thor dev kit (P3834-0008 module in P3740-0002 carrier with NVMe)

require conf/machine/include/igx-thor-t5000.inc

NVIDIA_WIFI ?= "kernel-module-rtk-btusb kernel-module-rtl8852ce"
require conf/machine/include/devkit-wifi.inc
require conf/machine/include/devkit-audio.inc
