#@TYPE: Machine
#@NAME: Nvidia AGX Thor dev kit
#@DESCRIPTION: Nvidia AGX Thor dev kit (P3834-0008 module in P4071-0000 carrier with NVMe)

require conf/machine/include/agx-thor-t5000.inc

require conf/machine/include/p4071.inc
