#@TYPE: Machine
#@NAME: Nvidia Jetson IGX Orin dev kit
#@DESCRIPTION: Nvidia Jetson IGX Orin dev kit (P3701-0008 module in P3740-0002 carrier)

TEGRA_BUPGEN_SPECS ?= "fab=300;boardsku=0008;boardrev=;chipsku=00:00:00:D0;bup_type=bl \
                       fab=300;boardsku=0008;boardrev=;bup_type=kernel"
KERNEL_DEVICETREE ?= "tegra234-p3740-0002+p3701-0008-nv.dtb"

require conf/machine/include/igx-orin.inc
require conf/machine/include/devkit-wifi.inc
require conf/machine/include/devkit-audio.inc
