REQUIRE_DISTRO_FEATURES_append_tegra = " x11"
PACKAGE_ARCH_tegra = "${TEGRA_PKGARCH}"
PACKAGECONFIG_remove_tegra = "wayland"
RRECOMMENDS_${PN}_remove_tegra = "mesa-vulkan-drivers"
RDEPENDS_${PN}_tegra = "tegra-libraries-vulkan"
