#! /bin/sh
DAEMON=/usr/sbin/nvpmodel
ARGS="-f /etc/nvpmodel.conf"
NAME=nvpmodel
DESC="Power model setup"

test -x $DAEMON || exit 0

case "$1" in
  start|restart)
      echo -n "Running $DESC: "
      $DAEMON $ARGS < /dev/null > /dev/null 2>&1 &
      echo "[OK]"
      ;;
  stop)
      ;;
  *)
      N=/etc/init.d/$NAME
      echo "Usage: $N {start|stop|restart}" >&2
      exit 1
      ;;
esac

exit 0
