MACHINE_EXTRA_RRECOMMENDS += " \
    kernel-module-tegra-aconnect \
    kernel-module-tegra210-adma \
    kernel-module-snd-soc-rl6231 \
    kernel-module-snd-soc-rt5640 \
    kernel-module-snd-soc-tegra-audio-graph-card \
    kernel-module-snd-soc-tegra210-ahub \
    kernel-module-snd-soc-tegra210-admaif \
    kernel-module-snd-soc-tegra210-i2s \
    kernel-module-snd-soc-tegra210-dmic \
    kernel-module-snd-soc-tegra210-mixer \
    kernel-module-snd-soc-tegra210-amx \
    kernel-module-snd-soc-tegra210-adx \
    kernel-module-snd-soc-tegra210-mvc \
    kernel-module-snd-soc-tegra210-sfc \
    kernel-module-snd-soc-tegra210-ope \
    kernel-module-snd-soc-tegra186-asrc \
    kernel-module-snd-soc-tegra186-dspk \
    nvidia-kernel-oot-alsa \
"
